name: unitary

on:
  pull_request:
  push:  # all

jobs:
  unitary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]

    name: "unit tests: python ${{ matrix.python-version }}"
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install Requirements
        run: |
          pip install -r dev-requirements.txt
          pip install .
          
          echo "$PATH"
          # Install zkvyper and era_test_node from binary repositories
          curl --location https://raw.githubusercontent.com/matter-labs/zkvyper-bin/66cc159d9b6af3b5616f6ed7199bd817bf42bf0a/linux-amd64/zkvyper-linux-amd64-musl-v1.4.0 \
            --silent --output /usr/local/bin/zkvyper && \
            chmod +x /usr/local/bin/zkvyper && \
            zkvyper --version
          curl --location https://github.com/matter-labs/era-test-node/releases/download/v0.1.0-alpha.19/era_test_node-v0.1.0-alpha.19-x86_64-unknown-linux-gnu.tar.gz \
            --silent --output era_test_node.tar.gz && \
            tar --extract --file=era_test_node.tar.gz && \
            mv era_test_node /usr/local/bin/era_test_node &&
            era_test_node --version && \
            rm era_test_node.tar.gz

      - name: Run Unit Tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: make test

      - name: Run Lint
        run: make lint
