on:
  release:
    types: [published]  # releases and pre-releases (release candidates)

jobs:
  publish-pypi:
    runs-on: ubuntu-latest

    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release

    steps:
    - uses: actions/checkout@v4

    - name: Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build

    - name: Build
      run: python -m build

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
